### ISSUE TITLE
Unable to find package.json for @react-rxjs/*

### ISSUE THREAD

**Issue by cabello** [re-rxjs/react-rxjs#198] opened 2021-05-17 20:41 UTC
Hi @josepot  👋 

I hope you are doing great!

I noticed while running `yarn storybook` the following warning:

```
WARN unable to find package.json for @react-rxjs/core
WARN unable to find package.json for @react-rxjs/utils
```

I know is just a warning and probably does not affect anything, I am also unsure how to address it because I did check your source files and I found the package.json for utils.

Nonetheless I thought you should know about this warning!

Take care,
:bow:

**Comment by josepot** [comment] 2021-05-21 09:53
Hi @cabello :wave: 

Thanks a lot for reporting this! Yeah, there is something definitely off with our current builds, we've also noticed some oddities while using `@react-rxjs/core` with node.js :thinking:

If you could please set up a basic repo that reproduces this issue, that would be a huge help for us :pray: Otherwise, I'm going to hope that the changes that we want to make for fixing the SSR issue also address this... :grimacing:

**Comment by voliva** [comment] 2021-06-09 08:23
Hey, I looked a bit into this issue, and I think it's on storybook.

There's quite [a few](https://github.com/storybookjs/storybook/issues/13114) issues [there](https://github.com/storybookjs/storybook/issues/14000) that show this same warning for different libraries, and in this one https://github.com/storybookjs/storybook/issues/13099 they recently fixed it.

I coudn't find what's the reason storybook would show this warning for some libraries, there were some workarounds but I didn't understand what was the underlying problem.

Anyway, I just tried it by upgrading storybook to the next version with `npx sb upgrade --prerelease` and the warning is gone 🎉  - I'm closing this issue, but let's open it back if we see it still causes other problems.

**Closed by voliva** 2021-06-09 08:23 UTC
